### ISSUE TITLE
Remove the filter from TermsStatsTable

### ISSUE THREAD

**Issue by sadasant** [smartprocure/contexture-react#104]
Perhaps it should be separated.

**Comment by daedalus28** [comment]
Yup, following the model of ResultsPager, etc.

Long term, I suspect we'll want a composable API like recharts has, where you'd do something like 

```js
<TermsStats>
  <Filter />
  <Table /> // Or <ChartThing />
</TermsStats>
```

Definitely a breaking change

**Comment by daedalus28** [comment]
This would be desirable if we had cases without the filter, but at this point, we also have the size selector and not a single case where we want to opt-out of the filter input.

The main reason do to this would be to avoid configuration like `{ hideFilter: true }`, but we'll wait until we have a use case for that before doing this.
