### ISSUE TITLE
React missing key prop warnings in ResultTable

### ISSUE THREAD

**Issue by doug-patterson** [smartprocure/contexture-react#106]
https://github.com/smartprocure/contexture-react/blob/master/src/exampleTypes/ResultTable.js#L59 is getting us a react warning when it turns out the `label`s aren't unique.

**Comment by daedalus28** [comment]
Interesting, that key doesn't even make sense there - it should be on the tr not the td

**Comment by doug-patterson** [comment]
@sadasant moved over to this repo. Since this is intended for general use we should probably support passing in the object path from which the key will be taken in all components that render arrays of items

**Comment by stellarhoof** [comment]
Fixed in https://github.com/smartprocure/contexture-react/pull/157
