### ISSUE TITLE
Fix second 'baseline' occurrence for facet checkboxes

### ISSUE THREAD

**Issue by doug-patterson** [smartprocure/contexture-react#126]
Need to change https://github.com/smartprocure/contexture-react/blob/master/src/exampleTypes/Facet.js#L92 corresponding to https://github.com/smartprocure/contexture-react/pull/123

**Comment by daedalus28** [comment]
This was merged but we should actually change it to align tops instead of centered if possible

**Comment by daedalus28** [comment]
Actually we're going to just discuss this later, disregard my comment.
