### ISSUE TITLE
Get this to Demo-able

### ISSUE THREAD

**Issue by daedalus28** [smartprocure/contexture-react#14]
- [x] SearchRoot needs to be able to take a path, e.g. `<SearchRoot tree={root} path={['root', 'criteria']} />`
- [x] Make some kind of functional field picker (text input box is fine)
- [x] Make facet example type functional (show context options as checkboxes and dispatch when checked or use a data reaction)
- [x] Make a functional query type (can be a text input mimicing "raw mode" and kill the words array thing we already have)

**Comment by daedalus28** [comment]
This should be about an hour or two and progress has started

**Comment by sadasant** [comment]
Done!
