### ISSUE TITLE
Better popover implementation

### ISSUE THREAD

**Issue by stellarhoof** [smartprocure/contexture-react#208]
Right now, our popover renders under the parent's DOM node, making it susceptible to clipping even with a large z-index. Moreover, it can mess up the layout when it shows since it occupies space. The solution is to use a react portal to move it out of its parent's DOM node but to also get a reference to it so it can render in the correct position. We might want to wait until we use react with hooks to make this easier.

Alternatively we could look into a library like https://github.com/alexkatz/react-tiny-popover
This one is pretty small: https://github.com/dbtek/react-popover

**Comment by stellarhoof** [comment]
We can use https://github.com/yjose/reactjs-popup

**Comment by daedalus28** [comment]
Solved by grey-vest v3
