### ISSUE TITLE
Kill Snapshots

### ISSUE THREAD

**Issue by daedalus28** [smartprocure/contexture-react#229]
It's been brought up a few times that jest snapshots in contexture-react add little value and are mostly just annoying. The only value they seem to provide is as a warning if you changed more DOM structure than you expected, but it seems like no one really looks at them anyway. Should we rip them out?

**Comment by stellarhoof** [comment]
They do have their value, but it's very easy for them to grow big and for people to not be clear as to what they're useful for. This article explains it better than I ever could: https://kentcdodds.com/blog/effective-snapshot-testing

**Comment by dubiousdavid** [comment]
Storybooks seem like the more valuable way to verify the components.

**Comment by doug-patterson** [comment]
+1

**Comment by daedalus28** [comment]
Yeah, they're really annoying. This is approved 👍
