### ISSUE TITLE
Implement relabelling groups in nested picker

### ISSUE THREAD

**Issue by doug-patterson** [smartprocure/contexture-react#232]
in cases where someone is systematically renaming schema fields they'll want to relabel the groups that emerge in the nested picker the same way. Currently the labels for these come from the schema keys here https://github.com/smartprocure/contexture-react/blob/master/src/layout/NestedPicker.js#L56 and can't be modified. We need to add a `mapSchemaKeysToGroupLabels` prop to the picker and pass it down into that flow, making sure it's exposed and passed down by components that invoke the picker

**Comment by daedalus28** [comment]
This is already supported by specifying a `path` on fields that determines where it goes in the field tree.

For example, `Organization.State` can be put under `Agency` by specifying path to `Agency.State`

So in fields where you might have this:
```js
{
  field: 'Organization.State',
  typeDefault: 'facet',
  // other stuff
}
```

You'd have this:

```js
{
  field: 'Organization.State',
  path: 'Agency.State',
  typeDefault: 'facet',
  // other stuff
}
```

You can do this dynamically/conditionally by only adding `path` if there's a part you're trying to rename which is helpful when doing this on the server.
