### ISSUE TITLE
InjectTreeNode props

### ISSUE THREAD

**Issue by dubiousdavid** [smartprocure/contexture-react#26]
We should consider prefixing prop names with an underscore. So `_tree` and `_node` to prevent unintended overwriting of the existing component props.

https://github.com/smartprocure/contexture-react/blob/master/src/example-types/components.js#L34-L37

**Comment by sadasant** [comment]
An alternative is something like this (as mentioned to me by @daedalus28):
```javascript
export let InjectTreeNode = inject(({ tree: t1 }, { tree = t1, path, node: n2 }) => ({
  tree,
  node: n2 || tree.getNode(path),
}))
```

**Comment by daedalus28** [comment]
Not really an alternative - it solves what I think is a bug in InjectTreeNode. David's point in general is about overriding prop names whereas my revision is about overriding the props themselves

**Comment by daedalus28** [comment]
But I do think that when you use InjectTreeNode, you have full control of the props your comment takes. And in general, if you're using InjectTreeNode, `node` is likely to most intuitively be the contexture tree node you're injecting and it's highly unlikely that a different prop would be more intuitive as `node` - but if that's what we're finding in real-world use cases, we can name it something less convenient but less likely to have collisions.
