### ISSUE TITLE
Search Bar Styling

### ISSUE THREAD

**Issue by daedalus28** [smartprocure/contexture-react#345]
Latest styling changes:

- [ ] Remove auto-collapse from TagsInput and move to only be in the new TagsQuerySearchBar (can be its own PR first that gets merged right away)
- [ ] Create a new ExampleType, `TagsQuerySearchBar`
- [ ] Add a new TagsInput that puts the text input always on top (like in #314), and use a nested theme key to target TagsInput on TagsQuerySearchBar
- [ ] Follow the mocks for the collapsed styling (similar to #314 except saying how many tags there are instead of just a caret)

**Comment by Akrion** [comment]
Moving to @michsa as per the standup discussion.

**Comment by daedalus28** [comment]
This is done now :)
