### ISSUE TITLE
Add moment to dependencies

### ISSUE THREAD

**Issue by michsa** [smartprocure/contexture-react#347]
It's used in GreyVest's `DateInput`, so it's required for both the contexture-react and grey-vest packages.

**Comment by UltimaBGD** [comment]
I can work on this if you would like.

**Comment by UltimaBGD** [comment]
Is there a particular version in mind?

**Comment by michsa** [comment]
Hey @UltimaBGD, welcome! 🤗

To answer your question, it looks like we're already using the [latest version](https://www.npmjs.com/package/moment) of moment, 2.2.4:

https://github.com/smartprocure/contexture-react/blob/317b7bff16b4bf9e9cda27828599cf767d86592f/package.json#L108

So the same version should be fine, the package just needs to be moved into the `dependencies` section instead.

**Comment by UltimaBGD** [comment]
Gotcha, will have a PR up shortly.

**Comment by michsa** [comment]
Closed by #348 🎉
