### ISSUE TITLE
Better Theming API

### ISSUE THREAD

**Issue by daedalus28** [smartprocure/contexture-react#98]
Right now, theming is accomplished by components allowing you to override inner components via props. We currently create themes by using `defaultProps` from `recompose` and just packaging up all of the components. This works but makes it difficult to customize themes from outside the theme itself since it relies on components within the closure of the theme files.

A potentially better option is to introduce support for getting components from props _or_ from a `contextureTheme` on context via `Provider`/`inject`. This would allow runtime changes of specific components so you could, for example, take the grey vest theme as is but just tweak one small thing externally instead of having to duplicate most of the theme. It would also make theming a bit more maintainable as you wouldn't import components from a theme (which makes it difficult to change a theme globally - somewhat defeating one of the main benefits of the theming concept), you'd use the contexture-react components directly and set the theme in the root of your app with Provider.

**Comment by daedalus28** [comment]
Some more context, it will look something like this:

```js
let theme = { TextInput: 'input', Loader: ReactSpinKitFancyLoaderThingy }

<Provider tree={search} contextureTheme={theme}>
  <ContextureReactStuff />
</Provider>
```


and then later:

```js
inject(
  (stores, props) => {
      let Checkbox = _.get('contextureTheme.Checkbox') ||  props.Checkbox || throw('No Checkbox Provided')
      //... etc
  }
)
```

**Comment by daedalus28** [comment]
We're actively working on this for 2.0 in #275 🎉 

This will use native React context and so there will be an exported `ContextureThemeProvider` instead of mobx-react's Provider

**Comment by michsa** [comment]
This is done 🙂
